services:
  - type: web
    name: jira-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: JIRA_URL
        value: https://yourcompany.atlassian.net
      - key: EMAIL
        value: your@email.com
      - key: API_TOKEN
        value: your_api_token
      - key: PROJECT_KEY
        value: AI
    pythonVersion: 3.10
